### ISSUE TITLE
허용되지 않은 C함수를 사용하지 않게 주의해 주세요

### ISSUE THREAD

**Issue by dltjwl123** [webservv/webserv#23]
예시로 atoi 같은 경우 C의 atoi와 cpp의 std::atoi가 구분되어 있습니다. 일단 std::가 붙지 않으면 모두 C 계열 함수이므로 주의해서 사용하여야 합니다.

**Comment by christie26** [comment]
앗 제가 atoi 를 사용했었는데, 그걸 고치신건가요? 앞으로 한번씩 더 확인하겠습니닷
