### ISSUE TITLE
Server class 의 멤버변수에 관해서

### ISSUE THREAD

**Issue by dltjwl123** [webservv/webserv#6]
int socket_fd;
sockaddr_in server_addr;
sockaddr_in client_addr;
pollfd poll_fd[256];
int num_connections;
   
위 목록은 현재 Server가 가지고 있는 멤버변수 목록입니다. 이 중에서 1회성이 아닌 지속적으로 Server instance가 들고 있어야 하는 내용이 아니라면 각 함수의 지역변수로 바꾸는 것이 어떨까 합니다.

예를 들어 sockaddr_in 의 경우 bind에서 1회성으로 사용되고 있는데 이를 지역변수로 변경하는 것이 어떨까 합니다.

**Comment by christie26** [comment]
이 이슈는 살려뒀다가 리팩토링할 때 수정하고 지우죠!
